---
- name: GET BIG-IP Token
  uri:
    url: "https://{{ extra_ip_mgt }}:{{ extra_port_mgt }}/mgmt/shared/authn/login"
    method: POST
    headers:
      Content-Type: application/json
    body: "{{ lookup('template','bigip_auth.jinja2') }}"
    body_format: json
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: auth

- name: GET BIG-IP SSLO category
  uri:
    url: "https://{{ extra_ip_mgt }}:{{ extra_port_mgt }}/mgmt/tm/sys/url-db/url-category/~Common~{{ extra_category }}"
    method: GET
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: category

- debug:
    var: category.json

- name: local - backup format
  set_fact:
    backup_urls:
      urls: "{{ category.json.urls }}"

- name: SET Consul - Backup SSLO category
  consul_kv:
    scheme: "{{extra_consul_agent_scheme}}"
    validate_certs: no
    host: "{{extra_consul_agent_ip}}"
    port: "{{extra_consul_agent_port}}"
    key: "{{ extra_consul_path_backup }}/{{ extra_category }}"
    value: "{{ backup_urls }}"

- name: local - set var urls
  set_fact:
    cur_urls: "{{ category.json.urls }}"

- debug:
    var: cur_urls

- name: local - set var new_url
  set_fact:
    new_urls: []

- name: local - url lookup
  set_fact:
    new_urls: "{{ new_urls +  [ item ] }}"
  loop: "{{ cur_urls }}"
  when: item.name != extra_url_name

- debug:
    var: new_urls

- name: local - append new URL
  set_fact:
    new_urls:
      urls: "{{ new_urls }}"

- debug:
    var: new_urls

- name: UPDATE BIG-IP SSLO category
  uri:
    url: "https://{{ extra_ip_mgt }}:{{ extra_port_mgt }}/mgmt/tm/sys/url-db/url-category/~Common~{{ extra_category }}"
    method: PATCH
    headers:
      Content-Type: application/json
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    body: "{{ new_urls }}"
    body_format: json
    timeout: 60
    status_code: 200, 202
    validate_certs: false

- name: SET Consul - Source of Truth - SSLO category
  consul_kv:
    scheme: "{{extra_consul_agent_scheme}}"
    validate_certs: no
    host: "{{extra_consul_agent_ip}}"
    port: "{{extra_consul_agent_port}}"
    key: "{{ extra_consul_path_source_of_truth }}/{{ extra_category }}"
    value: "{{ new_urls }}"

- name: GET Consul - Source of Truth value
  debug:
    msg: "{{ lookup('consul_kv', '{{ extra_consul_path_source_of_truth }}/{{ extra_category }}', scheme=extra_consul_agent_scheme, validate_certs='no', host=extra_consul_agent_ip, port=extra_consul_agent_port, datacenter=extra_consul_datacenter ) }}"





...
